parameters:
  name: ''
  displayName: ''
  vmImage: ''
  stepsTemplate: ''
 

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        dynamic_release:
          STATIC_LINK: "OFF"
          CMAKE_CONFIG: "Release"
    steps:
      - template: ${{ parameters.stepsTemplate }}
        parameters:
          ${{ if eq(parameters.vmImage, 'vs2017-win2016') }}:
            toolchain: vs2017
          ${{ if eq(parameters.vmImage, 'windows-2019') }}:
            toolchain: vs2019
      - template: ./pubcrosswin.yml
        parameters:
            vsProjFolder: 'C:/vcpkg/installed/x64-windows'
